### ISSUE TITLE
classify_host broken on WSL on Windows 10

### ISSUE THREAD

**Issue by ysangkok** [kyuupichan/aiorpcX#28]
I don't know if you want to worry about this, but I just wanted to make sure you saw it. I guess it could be considered a Python or a WSL bug.

It works on Python 3.8, but not on Python 3.6:

```
Exception in callback RSTransport.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle RSTransport.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/janus/.local/lib/python3.6/site-packages/aiorpcx/rawsocket.py", line 80, in connection_made
    self._remote_address = NetAddress(peername[0], peername[1])
  File "/home/janus/.local/lib/python3.6/site-packages/aiorpcx/util.py", line 126, in __init__
    self._host = classify_host(host)
  File "/home/janus/.local/lib/python3.6/site-packages/aiorpcx/util.py", line 77, in classify_host
    return ip_address(host)
  File "/usr/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: 'fe80::d87f:233f:c05f:d0cf%wifi1' does not appear to be an IPv4 or IPv6 address
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 721, in _read_ready
    self._protocol.data_received(data)
  File "/home/janus/.local/lib/python3.6/site-packages/aiorpcx/rawsocket.py", line 98, in data_received
    self.session.data_received(data)
AttributeError: 'NoneType' object has no attribute 'data_received'
Exception in callback _SelectorTransport._call_connection_lost(None)
handle: <Handle _SelectorTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 651, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/home/janus/.local/lib/python3.6/site-packages/aiorpcx/rawsocket.py", line 94, in connection_lost
    self._framer.fail(ConnectionLostError())
AttributeError: 'NoneType' object has no attribute 'fail'
```

**Comment by kyuupichan** [comment]
Where is this coming from: "fe80::d87f:233f:c05f:d0cf%wifi1"?

**Comment by SomberNight** [comment]
Note: seems to me that these zone indices are (somewhat?) standard:
https://tools.ietf.org/html/rfc4007#section-11.3
https://tools.ietf.org/html/rfc6874

On the other hand, python 3.7 itself does not recognise them as valid IP addresses:
```python
>>> import ipaddress
>>> ipaddress.ip_address("fe80::d87f:233f:c05f:d0cf%wifi1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python\Python37\lib\ipaddress.py", line 54, in ip_address
    address)
ValueError: 'fe80::d87f:233f:c05f:d0cf%wifi1' does not appear to be an IPv4 or IPv6 address
>>> ipaddress.ip_address("fe80::d87f:233f:c05f:d0cf")
IPv6Address('fe80::d87f:233f:c05f:d0cf')
```

**Comment by kyuupichan** [comment]
This should work in Python3.9 (https://docs.python.org/3.9/whatsnew/3.9.html#ipaddress) so I'm going to close this; if you want it please use Python3.9.
